# fly.toml app configuration file generated for cdn-owlebot on 2024-01-13T23:00:05+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "cdn-owlebot"
primary_region = "cdg"

[build]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
